logical_axis_rules: [
                      ['batch', 'data'],
                      ['activation_batch', 'data'],
                      ['activation_heads', 'tensor'],
                      ['mlp','tensor'],
                      ['heads', 'tensor'],
                      ['vocab', 'tensor'],
                      ['out_channels', 'tensor']
                    ]

data_sharding: [['data', 'tensor']]